exports.TYPES = {
    sword: 1,
    wand: 2,
    shield: 3,
};

exports.EVENTS = {
    onTurnOrderDetermination: 1,
    onGameStart: 2,
    onSelfTurnStart: 3,
    onEnemyTurnStart: 4,
    onAnyTurnStart: 5,
    onSelfTurnEnd: 6,
    onEnemyTurnEnd: 7,
    onAnyTurnEnd: 8,
    beforeSelfDamage: 9,
    afterSelfDamage: 10,
    beforeEnemyDamage: 11,
    afterEnemyDamage: 12,
    beforeSelfAttack: 13,
    afterSelfAttack: 14,
    beforeEnemyAttack: 15,
    afterEnemyAttack: 16,
};

exports.RARITIES = {
    common: 1,
    uncommon: 2,
    rare: 3,
    epic: 4,
    special: 6,
};

exports.CHARACTERS = [
    'Piros',
    'Sora',
    'Mimiru',
    'Alkaid',
    'Haseo',
    'Bordeaux',
    'Antares',
    'Shino',
    'Sakubo',
    'Midori',
    'BlackRose',
    'Kuhn',
    'Pi',
    'Azure Kite',
    'Endrance',
    'Ovan',
    'Terajima Ryoko',
    'Orca',
    'Sakaki',
    'Silabus',
    'Kite',
    'Yata',
    'Elk and Mia',
    'Gaspard',
    'Atoli',
    'Mai Minase',
    'Kaede',
    'Tabby',
    'Silver Knight',
    'Balmung',
    'Matsu',
    'BT',
    'Gabi',
    'Shugo',
    'Zelkova',
    'AIDA-Infected Sakaki',
    'Cubia',
    'AIDA-Infected Sirius',
    'Sirius',
    'Piros the 3rd',
    'Taihaku',
    'Phyllo',
    'Nala',
    'B-Set and Gord',
    'Subaru and Tsukasa',
    'Hiiragi',
    'Death Grunty',
    'Natsume',
    'TaN',
    'Mistral',
];
