exports.TYPES = {
    sword: 1,
    wand: 2,
    shield: 3,
};

exports.EVENTS = {
    gameStart: 1,
    turnStart: 2,
    selfDamage: 3,
    enemyDamage: 4,
};

exports.RARITIES = {
    common: 1,
    uncommon: 2,
    rare: 3,
    epic: 4,
    special: 6,
};

exports.CHARACTERS = [
    'Piros',
    'Sora',
    'Mimiru',
    'Alkaid',
    'Haseo',
    'Bordeaux',
    'Antares',
    'Shino',
    'Sakubo',
    'Midori',
    'BlackRose',
    'Kuhn',
    'Pi',
    'Azure Kite',
    'Endrance',
    'Ovan',
    'Terajima Ryoko',
    'Orca',
    'Sakaki',
    'Silabus',
    'Kite',
    'Yata',
    'Elk and Mia',
    'Gaspard',
    'Atoli',
    'Mai Minase',
    'Kaede',
    'Tabby',
    'Silver Knight',
    'Balmung',
    'Matsu',
    'BT',
    'Gabi',
    'Shugo',
    'Zelkova',
    'AIDA-Infected Sakaki',
    'Cubia',
    'AIDA-Infected Sirius',
    'Sirius',
    'Piros the 3rd',
    'Taihaku',
    'Phyllo',
    'Nala',
    'B-Set and Gord',
    'Subaru and Tsukasa',
    'Hiiragi',
    'Death Grunty',
    'Natsume',
    'TaN',
    'Mistral',
];
