const { TYPES, RARITIES } = require('./Constants');

module.exports = [
    {
        id: 1,
        name: 'Haseo at Dawn (黎明のハセヲ)',
        ability: 'None',
        capacity: 12,
        hp: 16,
        ap: 3,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 2,
        name: 'Kite (カイト)',
        ability: 'None',
        capacity: 10,
        hp: 16,
        ap: 3,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 3,
        name: 'Haseo the Black Rogue (黒衣の錬装士ハセヲ)',
        ability: 'None',
        capacity: 9,
        hp: 16,
        ap: 4,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 4,
        name: 'BlackRose (ブラックローズ)',
        ability: 'None',
        capacity: 11,
        hp: 11,
        ap: 3,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 5,
        name: 'Haseo the Terror of Death (死の恐怖ハセヲ)',
        ability: 'None',
        capacity: 6,
        hp: 20,
        ap: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 6,
        name: 'Pi - Raven (レイヴン　パイ)',
        ability: 'None',
        capacity: 8,
        hp: 17,
        ap: 3,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 7,
        name: 'Balmung (バルムンク)',
        ability: 'None',
        capacity: 7,
        hp: 15,
        ap: 4,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 8,
        name: 'Tabby - Twilight Brigade (黄昏の旅団　タビー)',
        ability: 'None',
        capacity: 12,
        hp: 14,
        ap: 1,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 9,
        name: 'Degenerating Haseo (堕とされしハセヲ)',
        ability: 'None',
        capacity: 7,
        hp: 23,
        ap: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 10,
        name: 'Shino - Twilight Brigade (黄昏の旅団　志乃)',
        ability: 'None',
        capacity: 14,
        hp: 16,
        ap: 2,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 11,
        name: 'Sakisaka - Twilight Brigade (黄昏の旅団　匂坂)',
        ability: 'None',
        capacity: 10,
        hp: 20,
        ap: 2,
        type: TYPES.wand,
        rarity: RARITIES.epic,
    },
    {
        id: 12,
        name: 'Haseo Counterattacks (反撃のハセヲ)',
        ability: 'None',
        capacity: 8,
        hp: 23,
        ap: 3,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 13,
        name: 'Gaspard - Canard (カナード　ガスパー)',
        ability: 'None',
        capacity: 11,
        hp: 15,
        ap: 2,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 14,
        name: 'Atoli - Moon Tree (月の樹　アトリ)',
        ability: 'None',
        capacity: 10,
        hp: 17,
        ap: 2,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 15,
        name: 'Sakubo - Trifle (トライフル　朔望)',
        ability: 'None',
        capacity: 10,
        hp: 10,
        ap: 2,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 16,
        name: 'Orca (オルカ)',
        ability: 'None',
        capacity: 9,
        hp: 11,
        ap: 4,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 17,
        name: 'Raid of New Punishers (新米撃剣士レイド)',
        ability: 'None',
        capacity: 6,
        hp: 29,
        ap: 1,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 18,
        name: 'Ovan the Wanderer (流雄のオーヴァン)',
        ability: 'None',
        capacity: 12,
        hp: 12,
        ap: 4,
        type: TYPES.shield,
        rarity: RARITIES.epic,
    },
    {
        id: 19,
        name: 'Tri-Edge (三爪痕)',
        ability: 'None',
        capacity: 5,
        hp: 25,
        ap: 5,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 20,
        name: 'Endrance the Exquisite (麗のエンデュランス)',
        ability: 'None',
        capacity: 13,
        hp: 10,
        ap: 3,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 21,
        name: 'Kuhn - Raven (レイヴン　クーン)',
        ability: 'None',
        capacity: 12,
        hp: 10,
        ap: 2,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 22,
        name: 'Bordeaux the Mad Blade (凶刃のボルドー)',
        ability: 'None',
        capacity: 8,
        hp: 24,
        ap: 2,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 23,
        name: 'Ovan the Twilight (黄昏の徒オーヴァン)',
        ability: 'None',
        capacity: 11,
        hp: 8,
        ap: 3,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 24,
        name: 'Mistral (ミストラル)',
        ability: 'None',
        capacity: 10,
        hp: 14,
        ap: 1,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 25,
        name: 'Silabus - Canard (カナード　シラバス)',
        ability: 'None',
        capacity: 9,
        hp: 18,
        ap: 2,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 86,
        name: 'Haseo the Silver Dual Gunner',
        ability: 'Shooting Squad',
        capacity: 12,
        hp: 14,
        ap: 3,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 87,
        name: 'Bordeaux in Distress',
        ability: 'AIDA Berserk',
        capacity: 6,
        hp: 22,
        ap: 4,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 88,
        name: 'Alkaid - Icolo',
        ability: "Emperor's Pride",
        capacity: 10,
        hp: 12,
        ap: 3,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 89,
        name: 'Cold-Hearted Saku',
        ability: 'AIDA Corrosion',
        capacity: 12,
        hp: 16,
        ap: 2,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 90,
        name: 'Kaede - Moon Tree',
        ability: 'Whirlwind Assault',
        capacity: 10,
        hp: 14,
        ap: 2,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 91,
        name: 'Sirius - Icolo',
        ability: "Emperor's Pride",
        capacity: 9,
        hp: 10,
        ap: 3,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 92,
        name: 'Sophora - Moon Tree',
        ability: 'Mobilize the Troops',
        capacity: 6,
        hp: 8,
        ap: 4,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 93,
        name: 'Twilight Knight Piros the 3rd',
        ability: 'Cross Counter',
        capacity: 8,
        hp: 12,
        ap: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 94,
        name: 'Beast Awakening Haseo',
        ability: 'Charge Ahead',
        capacity: 9,
        hp: 18,
        ap: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 95,
        name: 'Zelkova - Moon Tree',
        ability: "Kaede's Guard",
        capacity: 15,
        hp: 17,
        ap: 0,
        type: TYPES.wand,
        rarity: RARITIES.epic,
    },
    {
        id: 96,
        name: 'Sakaki Lost in Ambition',
        ability: 'AIDA Berserk',
        capacity: 8,
        hp: 18,
        ap: 4,
        type: TYPES.wand,
        rarity: RARITIES.epic,
    },
    {
        id: 97,
        name: 'Azure Orca',
        ability: 'Defensive Stance',
        capacity: 6,
        hp: 16,
        ap: 4,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 98,
        name: 'Avatar Awakening Haseo',
        ability: 'Gathering of the Strong',
        capacity: 11,
        hp: 10,
        ap: 3,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 99,
        name: 'Yata - Raven',
        ability: 'Ingenious Scheme',
        capacity: 10,
        hp: 12,
        ap: 2,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 100,
        name: 'Bo - Trifle',
        ability: 'Defensive Stance',
        capacity: 12,
        hp: 12,
        ap: 1,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 101,
        name: 'Sakaki - Moon Tree',
        ability: 'Shield Protection',
        capacity: 12,
        hp: 8,
        ap: 1,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 102,
        name: 'Hiiragi - Moon Tree',
        ability: 'Mobilize the Troops',
        capacity: 11,
        hp: 14,
        ap: 1,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 103,
        name: 'Tri-Edge Ovan',
        ability: 'AIDA Berserk',
        capacity: 7,
        hp: 20,
        ap: 6,
        type: TYPES.shield,
        rarity: RARITIES.epic,
    },
    {
        id: 104,
        name: 'Gabi - Kestrel',
        ability: "Gabi's Call",
        capacity: 11,
        hp: 16,
        ap: 4,
        type: TYPES.shield,
        rarity: RARITIES.epic,
    },
    {
        id: 105,
        name: 'Azure Balmung',
        ability: 'Charge Ahead',
        capacity: 6,
        hp: 12,
        ap: 5,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 106,
        name: 'Card King Gaspard',
        ability: 'Change Ring',
        capacity: 12,
        hp: 12,
        ap: 2,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 107,
        name: 'Taihaku - Icolo',
        ability: 'Demon Sword Maxwell',
        capacity: 7,
        hp: 10,
        ap: 4,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 108,
        name: 'Antares - Icolo',
        ability: "Emperor's Pride",
        capacity: 8,
        hp: 12,
        ap: 3,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 109,
        name: 'Nala - Moon Tree',
        ability: 'Promised Discretion',
        capacity: 9,
        hp: 10,
        ap: 12,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 110,
        name: 'Matsu - Moon Tree',
        ability: 'Snipe Thunder',
        capacity: 7,
        hp: 10,
        ap: 3,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
];
