const { TYPES, RARITIES } = require('./Constants');

module.exports = [
    {
        id: 26,
        set: 1,
        name: 'Kappa Rappa Kappa',
        ability: 'Whirlwind Assault',
        characters: 'Piros',
        cost: 1,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 27,
        set: 1,
        name: 'Bamyon!',
        ability: "Mind's Eye",
        characters: 'Sora',
        cost: 1,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 28,
        set: 1,
        name: 'What Was That?!',
        ability: 'Quick Lightning',
        characters: 'Mimiru',
        cost: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 29,
        set: 1,
        name: 'Climactic Theory',
        ability: 'Whirlwind Assault',
        characters: 'Alkaid',
        cost: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 30,
        set: 1,
        name: 'The Trinity',
        ability: 'Charge Ahead',
        characters: 'Haseo',
        cost: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 31,
        set: 1,
        name: 'March of Destruction',
        ability: 'Vengeful Arrow',
        characters: 'Bordeaux',
        cost: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 32,
        set: 1,
        name: 'Falling Flag',
        ability: 'Momentary Glory',
        characters: 'Antares',
        cost: 2,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 33,
        set: 1,
        name: 'Fearful Shino',
        ability: 'Veil of Aura',
        characters: 'Shino',
        cost: 3,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 34,
        set: 1,
        name: 'Time of Peace',
        ability: 'Whirlwind Assault',
        characters: 'Sakubo',
        cost: 3,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 35,
        set: 1,
        name: 'Unreaching Blade',
        ability: "Mind's Eye",
        characters: 'Midori',
        cost: 3,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 36,
        set: 1,
        name: 'Black Rose of Insight',
        ability: 'Charge Ahead',
        characters: 'BlackRose',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 37,
        set: 1,
        name: 'Passing Through',
        ability: 'Quick Lightning',
        characters: 'Sakubo',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 38,
        set: 1,
        name: 'Iron Fist of Anger',
        ability: 'Hammer of Undoing',
        characters: 'Kuhn',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 39,
        set: 1,
        name: 'Unyielding Sparks',
        ability: 'Merciless Light',
        characters: 'Pi',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 40,
        set: 1,
        name: 'Treasonous Self',
        ability: 'Divine Punishment',
        characters: 'Haseo',
        cost: 5,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 41,
        set: 1,
        name: 'Thirst for Justice',
        ability: 'Price of Insight',
        characters: 'Kuhn',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 42,
        set: 1,
        name: 'Flame of Consumption',
        ability: 'Divine Punishment',
        characters: 'Azure Kite',
        cost: 6,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 43,
        set: 1,
        name: 'Decapitation of Oath',
        ability: 'Demonic Spear',
        characters: 'Azure Kite',
        cost: 7,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 44,
        set: 1,
        name: '"She"',
        ability: 'Estranged Self',
        characters: 'Endrance',
        cost: 6,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 45,
        set: 1,
        name: 'Baptism of Smiles',
        ability: 'Border of Zero',
        characters: 'Ovan',
        cost: 7,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 46,
        set: 1,
        name: 'Wrath of Logos',
        ability: 'Shield Protection',
        characters: 'Pi',
        cost: 1,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 47,
        set: 1,
        name: "Young Girl's Path",
        ability: 'Vitality Medicine',
        characters: 'Terajima Ryoko',
        cost: 1,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 48,
        set: 1,
        name: "Azure Sea's Laugh",
        ability: 'Energy Genome',
        characters: 'Orca',
        cost: 1,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 49,
        set: 1,
        name: 'Voluntary Trust',
        ability: 'Spirit Clothes',
        characters: 'Sakaki',
        cost: 2,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 50,
        set: 1,
        name: 'Come Back Alive',
        ability: 'Clenching Teeth',
        characters: 'Silabus',
        cost: 2,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 51,
        set: 1,
        name: 'Aurora Gaze',
        ability: 'Shield Protection',
        characters: 'Kite',
        cost: 2,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 52,
        set: 1,
        name: 'Refrain of Shadows',
        ability: 'Grief of Comrade',
        characters: 'Yata',
        cost: 2,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 53,
        set: 1,
        name: "Coppelia's Repose",
        ability: "Anu's Karma",
        characters: 'Elk and Mia',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 54,
        set: 1,
        name: 'Rival Spirits',
        ability: 'Warning Harmony',
        characters: 'Sakubo',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 55,
        set: 1,
        name: 'A Time To Love',
        ability: 'Shield Protection',
        characters: 'Gaspard',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 56,
        set: 1,
        name: 'With My Brother',
        ability: 'Spirit Clothes',
        characters: 'Sakubo',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 57,
        set: 1,
        name: 'Shadow of Memories',
        ability: 'Vitality Medicine',
        characters: 'Atoli',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 58,
        set: 1,
        name: 'Freedom to Imagine',
        ability: "Anu's Karma",
        characters: 'Gaspard',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 59,
        set: 1,
        name: 'Healing Waves',
        ability: 'Immortal Genome',
        characters: 'Atoli',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 60,
        set: 1,
        name: 'Ace of Hearts',
        ability: 'Verboten Libation',
        characters: 'Atoli',
        cost: 5,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 61,
        set: 1,
        name: 'Invisible',
        ability: 'Veil of Aura',
        characters: 'Haseo',
        cost: 6,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 62,
        set: 1,
        name: 'Restraint of Discipline',
        ability: 'Filling Hollow',
        characters: 'Pi',
        cost: 5,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 63,
        set: 1,
        name: 'No More Loss',
        ability: 'Warning Harmony',
        characters: 'Haseo',
        cost: 6,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 64,
        set: 1,
        name: 'Melody Pursuer',
        ability: 'Time Torrent',
        characters: 'Mai Minase',
        cost: 6,
        type: TYPES.wand,
        rarity: RARITIES.epic,
    },
    {
        id: 65,
        set: 1,
        name: 'Impenetrable Barrier',
        ability: 'Mirror of Revenge',
        characters: 'Shino',
        cost: 7,
        type: TYPES.wand,
        rarity: RARITIES.epic,
    },
    {
        id: 66,
        set: 1,
        name: 'Unstoppable Resolve',
        ability: 'Snipe Thunder',
        characters: 'Kaede',
        cost: 1,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 67,
        set: 1,
        name: 'Cat Punch!!',
        ability: 'Fire Fang',
        characters: 'Tabby',
        cost: 1,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 68,
        set: 1,
        name: 'Bird in a Cage',
        ability: 'Energy Drain',
        characters: 'Sakaki',
        cost: 1,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 69,
        set: 1,
        name: 'Master Subaru!',
        ability: "Folset's Trial",
        characters: 'Silver Knight',
        cost: 2,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 70,
        set: 1,
        name: 'Jackpot',
        ability: 'Snipe Thunder',
        characters: 'Kuhn',
        cost: 2,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 71,
        set: 1,
        name: 'Angry Blue Sky',
        ability: 'Flame Fang',
        characters: 'Balmung',
        cost: 2,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 72,
        set: 1,
        name: 'PK Network',
        ability: 'All At Once',
        characters: 'Bordeaux',
        cost: 2,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 73,
        set: 1,
        name: 'Two Fangs',
        ability: 'Bone Crunching',
        characters: 'Matsu',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 74,
        set: 1,
        name: 'Gimme Some Chim!',
        ability: 'Snipe Thunder',
        characters: 'Haseo',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 75,
        set: 1,
        name: 'Bland Self',
        ability: 'Change Ring',
        characters: 'BT',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 76,
        set: 1,
        name: 'Order Upheld',
        ability: 'Flame Fang',
        characters: 'Balmung',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 77,
        set: 1,
        name: 'Rose Letters',
        ability: 'Aurora Tears',
        characters: 'Endrance',
        cost: 4,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 78,
        set: 1,
        name: 'Reckless Roar',
        ability: 'Bone Crunching',
        characters: 'BlackRose',
        cost: 4,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 79,
        set: 1,
        name: 'Check This Out!',
        ability: 'All At Once',
        characters: 'Atoli',
        cost: 5,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 80,
        set: 1,
        name: 'Broken Full Moon',
        ability: 'Meeting of Souls',
        characters: 'Sakubo',
        cost: 4,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 81,
        set: 1,
        name: 'Dancing Lion',
        ability: 'Will of Similars',
        characters: 'Gabi',
        cost: 5,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 82,
        set: 1,
        name: "Don't Kick!!",
        ability: 'Trial By Fire',
        characters: 'Haseo',
        cost: 6,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 83,
        set: 1,
        name: 'Officially Allowed',
        ability: 'Quickdance',
        characters: 'Shugo',
        cost: 6,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 84,
        set: 1,
        name: 'Strongest Smile',
        ability: "Twilight's Call",
        characters: 'Zelkova',
        cost: 6,
        type: TYPES.shield,
        rarity: RARITIES.epic,
    },
    {
        id: 85,
        set: 1,
        name: "Grim Reaper's Rondo",
        ability: "Avatar's Descent",
        characters: 'Haseo',
        cost: 7,
        type: TYPES.shield,
        rarity: RARITIES.epic,
    },
    {
        id: 111,
        set: 2,
        name: 'Zelpest Light Blast',
        ability: 'Double Trigger',
        characters: 'Haseo',
        cost: 7,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 112,
        set: 2,
        name: 'Promised Power',
        ability: 'AIDA Berserk',
        characters: 'AIDA-Infected Sakaki',
        cost: 6,
        type: TYPES.sword,
        rarity: RARITIES.epic,
    },
    {
        id: 113,
        set: 2,
        name: 'A Road to Change',
        ability: 'Blades Crossing',
        characters: 'Haseo',
        cost: 6,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 114,
        set: 2,
        name: "Pandora's Box",
        ability: 'AIDA Berserk',
        characters: 'Ovan',
        cost: 5,
        type: TYPES.sword,
        rarity: RARITIES.rare,
    },
    {
        id: 115,
        set: 2,
        name: 'Pure Malice',
        ability: 'Light of Annihilation',
        characters: 'Cubia',
        cost: 5,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 116,
        set: 2,
        name: 'Howling Fang',
        ability: 'Reckless Rewards',
        characters: 'Haseo',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 117,
        set: 2,
        name: 'A Promise of Discord',
        ability: 'Momentary Glory',
        characters: 'AIDA-Infected Sirius',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 118,
        set: 2,
        name: 'The Second Seal',
        ability: 'Avatar Berserk',
        characters: 'Haseo',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.uncommon,
    },
    {
        id: 119,
        set: 2,
        name: "I'm not your pupil!",
        ability: 'First to Action',
        characters: 'Antares',
        cost: 4,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 120,
        set: 2,
        name: 'Minimum Maxim',
        ability: 'Hammer of Undoing',
        characters: 'Sirius',
        cost: 3,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 121,
        set: 2,
        name: 'Heavenly Twilight Knight',
        ability: 'Golden Spear',
        characters: 'Piros the 3rd',
        cost: 3,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 122,
        set: 2,
        name: 'Hurricane Knight',
        ability: 'Charge Ahead',
        characters: 'Haseo',
        cost: 3,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 123,
        set: 2,
        name: 'The Vain King',
        ability: 'First Striike',
        characters: 'Taihaku',
        cost: 3,
        type: TYPES.sword,
        rarity: RARITIES.common,
    },
    {
        id: 124,
        set: 2,
        name: "What's Most Important",
        ability: 'Long-awaited Return',
        characters: 'Shino',
        cost: 7,
        type: TYPES.wand,
        rarity: RARITIES.epic,
    },
    {
        id: 125,
        set: 2,
        name: 'Operation Delta',
        ability: 'Telepathy',
        characters: 'Haseo',
        cost: 6,
        type: TYPES.wand,
        rarity: RARITIES.epic,
    },
    {
        id: 126,
        set: 2,
        name: 'Overture of Destruction',
        ability: 'Filling Hollow',
        characters: 'Atoli',
        cost: 6,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 127,
        set: 2,
        name: 'Playful Hermit',
        ability: 'Pattern of Demons',
        characters: 'Yata',
        cost: 5,
        type: TYPES.wand,
        rarity: RARITIES.rare,
    },
    {
        id: 128,
        set: 2,
        name: 'Flame Guardian',
        ability: "Anu's Karma",
        characters: 'Atoli',
        cost: 5,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 129,
        set: 2,
        name: 'Did you see that!',
        ability: 'Ingenious Scheme',
        characters: 'Phyllo',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 130,
        set: 2,
        name: 'Magic Surge',
        ability: 'Detail Oriented',
        characters: 'Sakubo',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 131,
        set: 2,
        name: 'Limitless Knowledge',
        ability: 'Different Mix',
        characters: 'Yata',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.uncommon,
    },
    {
        id: 132,
        set: 2,
        name: 'Masquerade Ball',
        ability: 'Promised Discretion',
        characters: 'Nala',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 133,
        set: 2,
        name: 'Serpentarius',
        ability: 'Teamwork',
        characters: 'Pi',
        cost: 4,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 134,
        set: 2,
        name: 'A Time for Calm',
        ability: 'Immortal Genome',
        characters: 'Midori',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 135,
        set: 2,
        name: "Remorse's Companion",
        ability: 'Detail Oriented',
        characters: 'B-Set and Gord',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 136,
        set: 2,
        name: 'Our Best Shot',
        ability: 'Defensive Stance',
        characters: 'Silabus',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 137,
        set: 2,
        name: 'Miracle',
        ability: 'Teamwork',
        characters: 'Subaru and Tsukasa',
        cost: 3,
        type: TYPES.wand,
        rarity: RARITIES.common,
    },
    {
        id: 138,
        set: 2,
        name: 'Ultimate Thanatos',
        ability: 'Massacre Pulse',
        characters: 'Haseo',
        cost: 7,
        type: TYPES.shield,
        rarity: RARITIES.epic,
    },
    {
        id: 139,
        set: 2,
        name: 'A False Future',
        ability: 'Rendezvous',
        characters: 'Ovan',
        cost: 6,
        type: TYPES.shield,
        rarity: RARITIES.epic,
    },
    {
        id: 140,
        set: 2,
        name: 'Creatures From the Dark',
        ability: 'Suck it Up',
        characters: 'Azure Kite',
        cost: 6,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 141,
        set: 2,
        name: 'Chaotic Answer',
        ability: 'Avatar Berserk',
        characters: 'Ovan',
        cost: 6,
        type: TYPES.shield,
        rarity: RARITIES.rare,
    },
    {
        id: 142,
        set: 2,
        name: 'Cheer Up',
        ability: 'Quickdfance',
        characters: 'Alkaid',
        cost: 5,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 143,
        set: 2,
        name: 'A Glimpse of Twins',
        ability: 'Harmonic Rhythm',
        characters: 'Sakubo',
        cost: 4,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 144,
        set: 2,
        name: 'Next to You, Next to Me',
        ability: 'Fused Consciousness',
        characters: 'Elk and Mia',
        cost: 4,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 145,
        set: 2,
        name: 'Together with the Master',
        ability: 'Will of Similars',
        characters: 'Tabby',
        cost: 4,
        type: TYPES.shield,
        rarity: RARITIES.uncommon,
    },
    {
        id: 146,
        set: 2,
        name: "A Girl's Heart",
        ability: "Folset's Trial",
        characters: 'Hiiragi',
        cost: 4,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 147,
        set: 2,
        name: 'Grunty Oink!',
        ability: 'Aurora Tears',
        characters: 'Death Grunty',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 148,
        set: 2,
        name: "A Hero's Arrival!",
        ability: 'Cross Counter',
        characters: 'Natsume',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 149,
        set: 2,
        name: 'The Place for Evil',
        ability: 'Teamwork',
        characters: 'TaN',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
    {
        id: 150,
        set: 2,
        name: 'Cute Hunter',
        ability: 'Energy Drain',
        characters: 'Mistral',
        cost: 3,
        type: TYPES.shield,
        rarity: RARITIES.common,
    },
];
